version: '3.8'
services:
  redis:
    image: redis:6.0.9-alpine
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - .:/data
    command: redis-server /data/redis.conf
    restart: always
